name: My First GitHub Action

on: 
 push:
  branches:
    - main


jobs:
  first-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print Hello Message
        run: echo "Hello Faheem"

      - name: Print GitHub Action Message
        run: echo "Testing Again!"

      - name: Print GitHub Action Message
        run: echo "Git Hub Action is running successfully!"